<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\User;
use Carbon\Carbon;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //INSERTAMOS LOS USUARIOS DE PRUEBA
        $usuario = User::create([
            'numSocio' => '1',
            'altaSocio' => Carbon::now()->addMonths(-1),
            'bajaSocio' => null,
            'nombre' => ' Rowan',
            'primerApellido' => 'Atkinson',
            'segundoApellido' => '',
            'DNI' => '00000001X',
            'sexo' => 'varon',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "06-01-1955", 'Europe/Madrid'),
            'direccion' => 'Calle de Mr. Bean, 1',
            'localidad' => 'Madrid',
            'provincia' => 'Madrid',
            'codPostal' => 28028,
            'telefono' => '666000111',
            'email' => 'admin@asogest.com',
            'password' => bcrypt('Admin1234'),
            'foto' => 'Testadmin.jpg',
            'invitaciones' => '6',
            'username' => 'admin',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => true,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('admin');

        $usuario = User::create([
            'numSocio' => '2',
            'altaSocio' => Carbon::now()->addMonths(-2),
            'bajaSocio' => null,
            'nombre' => 'Arnold',
            'primerApellido' => 'Schwarzenegger',
            'segundoApellido' => '',
            'DNI' => '00000002X',
            'sexo' => 'varon',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "30-07-1947", 'Europe/Madrid'),
            'direccion' => 'Avenida de Conan el Bárbaro, 2',
            'localidad' => 'Madrid',
            'provincia' => 'Madrid',
            'codPostal' => 28028,
            'telefono' => '666000222',
            'email' => 'conan@asogest.com',
            'password' => bcrypt('tesorero1234'),
            'foto' => 'Testtesorero.jpg',
            'invitaciones' => '6',
            'username' => 'tesorero',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => true,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('tesorero');

        $usuario = User::create([
            'numSocio' => '3',
            'altaSocio' => Carbon::now()->addMonths(-3),
            'bajaSocio' => null,
            'nombre' => 'Scarlett',
            'primerApellido' => 'Johansson ',
            'segundoApellido' => '',
            'DNI' => '00000003X',
            'sexo' => 'mujer',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "22-11-1984", 'Europe/Madrid'),
            'direccion' => 'Calle de la Viuda Negra, 3',
            'localidad' => 'Madrid',
            'provincia' => 'Madrid',
            'codPostal' => 28028,
            'telefono' => '666000333',
            'email' => 'viudanegra@asogest.com',
            'password' => bcrypt('secretario1234'),
            'foto' => 'Testsecretario.jpg',
            'invitaciones' => '6',
            'username' => 'secretario',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => true,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('secretario');

        $usuario = User::create([
            'numSocio' => '4',
            'altaSocio' => Carbon::now()->addMonths(-12),
            'bajaSocio' => null,
            'nombre' => 'Steven Grant',
            'primerApellido' => 'Rogers',
            'segundoApellido' => '',
            'DNI' => '00000004X',
            'sexo' => 'varon',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "04-07-1918", 'Europe/Madrid'),
            'direccion' => 'Plaza del Capitán América, 4',
            'localidad' => 'Madrid',
            'provincia' => 'Madrid',
            'codPostal' => 28028,
            'telefono' => '666000444',
            'email' => 'capitan@asogest.com',
            'password' => bcrypt('capitan1234'),
            'foto' => 'TestSocio4.jpg',
            'invitaciones' => '6',
            'username' => 'capitan',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => true,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('socio');

        $usuario = User::create([
            'numSocio' => '5',
            'altaSocio' => Carbon::now(),
            'bajaSocio' => null,
            'nombre' => 'Robert Bruce',
            'primerApellido' => 'Banner',
            'segundoApellido' => '',
            'DNI' => '00000005X',
            'sexo' => 'varon',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "01-05-1962", 'Europe/Madrid'),
            'direccion' => 'Calle de Hulk, 5',
            'localidad' => 'Madrid',
            'provincia' => 'Madrid',
            'codPostal' => 28028,
            'telefono' => '666000555',
            'email' => 'hulk@asogest.com',
            'password' => bcrypt('hulk1234'),
            'foto' => 'TestSocio5.jpg',
            'invitaciones' => '6',
            'username' => 'hulk',
            'habilitado' => false,
            'accesoDrive' => false,
            'accesoJunta' => false,
            'recibirCorreos' => false,
            'privacidad' => false,
        ]);
        $usuario->assignRole('socio');

        $usuario = User::create([
            'numSocio' => '6',
            'altaSocio' => Carbon::now()->addMonths(-12),
            'bajaSocio' => null,
            'nombre' => 'Ryan',
            'primerApellido' => 'Reynolds',
            'segundoApellido' => '',
            'DNI' => '00000006X',
            'sexo' => 'varon',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "23-10-1976", 'Europe/Madrid'),
            'direccion' => 'Avenida de Deadpool, 6',
            'localidad' => 'Madrid',
            'provincia' => 'Madrid',
            'codPostal' => 28028,
            'telefono' => '666000666',
            'email' => 'deadpool@asogest.com',
            'password' => bcrypt('deadpool1234'),
            'foto' => 'TestSocio6.jpg',
            'invitaciones' => '6',
            'username' => 'deadpool',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => false,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('socio');

        $usuario = User::create([
            'numSocio' => '7',
            'altaSocio' => Carbon::now(),
            'bajaSocio' => null,
            'nombre' => 'Sandra',
            'primerApellido' => 'Bullock',
            'segundoApellido' => '',
            'DNI' => '00000007X',
            'sexo' => 'mujer',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "26-07-1964", 'Europe/Madrid'),
            'direccion' => 'Calle de la Red, 6',
            'localidad' => 'Madrid',
            'provincia' => 'Madrid',
            'codPostal' => 28028,
            'telefono' => '666000777',
            'email' => 'lared@asogest.com',
            'password' => bcrypt('sandra1234'),
            'foto' => 'TestSocio7.jpg',
            'invitaciones' => '6',
            'username' => 'sandra',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => false,
            'recibirCorreos' => false,
            'privacidad' => false,
        ]);
        $usuario->assignRole('socio');

        $usuario = User::create([
            'numSocio' => '8',
            'altaSocio' => Carbon::now()->addMonths(-12),
            'bajaSocio' => null,
            'nombre' => 'Anakin',
            'primerApellido' => 'Skywalker',
            'segundoApellido' => '',
            'DNI' => '00000008X',
            'sexo' => 'varon',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "04-06-1980", 'Europe/Madrid'),
            'direccion' => 'Estrella de la Muerte s/n',
            'localidad' => 'Madrid',
            'provincia' => 'Madrid',
            'codPostal' => 28028,
            'telefono' => '666000888',
            'email' => 'darthvader@asogest.com',
            'password' => bcrypt('jedi1234'),
            'foto' => 'TestSocio8.jpg',
            'invitaciones' => '6',
            'username' => 'jedi',
            'habilitado' => true,
            'accesoDrive' => false,
            'accesoJunta' => true,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('socio');

        $usuario = User::create([
            'numSocio' => '9',
            'altaSocio' => Carbon::now()->addMonths(-9),
            'bajaSocio' => null,
            'nombre' => 'Harry',
            'primerApellido' => 'Potter',
            'segundoApellido' => '',
            'DNI' => '00000009X',
            'sexo' => 'varon',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "31-07-1980", 'Europe/Madrid'),
            'direccion' => 'Privet Drive, 4',
            'localidad' => 'Little Winngs',
            'provincia' => 'Inglaterra',
            'codPostal' => 28028,
            'telefono' => '666000999',
            'email' => 'harry@asogest.com',
            'password' => bcrypt('harry1234'),
            'foto' => 'TestSocio9.jpg',
            'invitaciones' => '6',
            'username' => 'potter',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => true,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('socio');

        $usuario = User::create([
            'numSocio' => '10',
            'altaSocio' => Carbon::now()->addMonths(-9),
            'bajaSocio' => null,
            'nombre' => 'Ron',
            'primerApellido' => 'Weasley',
            'segundoApellido' => '',
            'DNI' => '00000010X',
            'sexo' => 'varon',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "01-03-1980", 'Europe/Madrid'),
            'direccion' => 'La Madriguera',
            'localidad' => 'Ottery St. Catchpole',
            'provincia' => 'Inglaterra',
            'codPostal' => 28028,
            'telefono' => '666001010',
            'email' => 'ron@asogest.com',
            'password' => bcrypt('ron1234'),
            'foto' => 'TestSocio10.jpg',
            'invitaciones' => '6',
            'username' => 'ron',
            'habilitado' => true,
            'accesoDrive' => false,
            'accesoJunta' => false,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('socio');

        $usuario = User::create([
            'numSocio' => '11',
            'altaSocio' => Carbon::now()->addMonths(-9),
            'bajaSocio' => null,
            'nombre' => 'Hermione',
            'primerApellido' => 'Granger',
            'segundoApellido' => '',
            'DNI' => '00000011X',
            'sexo' => 'mujer',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "19-09-1979", 'Europe/Madrid'),
            'direccion' => '',
            'localidad' => '',
            'provincia' => 'Inglaterra',
            'codPostal' => 28028,
            'telefono' => '666001111',
            'email' => 'hermy@asogest.com',
            'password' => bcrypt('hermi1234'),
            'foto' => 'TestSocio11.jpg',
            'invitaciones' => '6',
            'username' => 'hermi',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => true,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('socio');

        $usuario = User::create([
            'numSocio' => '12',
            'altaSocio' => Carbon::now(),
            'bajaSocio' => null,
            'nombre' => 'Optimus',
            'primerApellido' => 'Prime',
            'segundoApellido' => '',
            'DNI' => '00000012X',
            'sexo' => 'nodefinido',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "1-4-2000", 'Europe/Madrid'),
            'direccion' => '',
            'localidad' => '',
            'provincia' => 'Cybertron',
            'codPostal' => 28028,
            'telefono' => '666001212',
            'email' => 'optimus@asogest.com',
            'password' => bcrypt('autobot1234'),
            'foto' => '',
            'invitaciones' => '6',
            'username' => 'autobot',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => true,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('socio');

        $usuario = User::create([
            'numSocio' => '13',
            'altaSocio' => Carbon::now(),
            'bajaSocio' => null,
            'nombre' => 'Pumuky',
            'primerApellido' => 'Kobold',
            'segundoApellido' => '',
            'DNI' => '00000013X',
            'sexo' => 'varon',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "01-02-1961", 'Europe/Madrid'),
            'direccion' => 'El Taller de Eder',
            'localidad' => '',
            'provincia' => '',
            'codPostal' => 28028,
            'telefono' => '666001313',
            'email' => 'pumuky@asogest.com',
            'password' => bcrypt('duende1234'),
            'foto' => 'TestSocio13.jpg',
            'invitaciones' => '6',
            'username' => 'duende',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => true,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('socio');

        $usuario = User::create([
            'numSocio' => '14',
            'altaSocio' => Carbon::now(),
            'bajaSocio' => null,
            'nombre' => 'Stephen Vincent',
            'primerApellido' => 'Strange',
            'segundoApellido' => '',
            'DNI' => '00000014X',
            'sexo' => 'varon',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "10-07-1963", 'Europe/Madrid'),
            'direccion' => 'Calle del Hechicero supremo, 14',
            'localidad' => 'Madrid',
            'provincia' => 'Madrid',
            'codPostal' => 28028,
            'telefono' => '666001414',
            'email' => 'drstrange@asogest.com',
            'password' => bcrypt('Mago1234*'),
            'foto' => 'TestSocio14.jpg',
            'invitaciones' => '6',
            'username' => 'strange',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => true,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('socio');

        $usuario = User::create([
            'numSocio' => '15',
            'altaSocio' => Carbon::now(),
            'bajaSocio' => null,
            'nombre' => 'Jennifer Love',
            'primerApellido' => 'Hewitt',
            'segundoApellido' => '',
            'DNI' => '00000015X',
            'sexo' => 'mujer',
            'fnacimiento' => Carbon::createFromFormat('d-m-Y', "21-02-1979", 'Europe/Madrid'),
            'direccion' => 'Paseo de los Espíritus,15',
            'localidad' => 'Madrid',
            'provincia' => 'Madrid',
            'codPostal' => 28028,
            'telefono' => '666001515',
            'email' => 'lovehewitt@asogest.com',
            'password' => bcrypt('fantasmas1234'),
            'foto' => 'TestSocio15.jpg',
            'invitaciones' => '6',
            'username' => 'fantasmas',
            'habilitado' => true,
            'accesoDrive' => true,
            'accesoJunta' => true,
            'recibirCorreos' => true,
            'privacidad' => true,
        ]);
        $usuario->assignRole('socio');

    }
}
